import type { NextPage } from 'next'
import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Nav } from '../src/Nav/Nav';
import Link from 'next/link';

const Home: NextPage = () => {

  const landingUrl = process.env.NEXT_PUBLIC_LANDING_PAGE_BASE_URL as string;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <h1 className={styles.title}>
          Dashboard
        </h1>
        <Link href="/settings">Settings</Link>
        <Link href={landingUrl}>Sign out</Link>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            {/*<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />*/}
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getStaticProps() {
  return {
    props: {

    }
  }
}

export default Home
