import type { NextPage } from 'next'
import styles from '../styles/Home.module.css'
import Head from 'next/head';
import Link from 'next/link';

const Settings: NextPage = () => {

  const landingUrl = process.env.NEXT_PUBLIC_LANDING_PAGE_BASE_URL as string;

  return (
    <div className={ styles.container }>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main className={ styles.main }>


        {/*<Nav/>*/}

        <h1 className={ styles.title }>
          Settings
        </h1>
        <Link href="/">Dashboard</Link>
        <Link href={landingUrl}>Sign out</Link>
      </main>

      <footer className={ styles.footer }>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{ ' ' }
          <span className={ styles.logo }>
            {/*<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />*/ }
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getServerSideProps() {
  return {
    props: {

    }
  }
}

export default Settings
